import type { Preset } from './types';

export const DEFAULT_CONFIG = {
  companyName: 'Reezma Hanan',
  companyNameColor: '#ffffff',
  companyNameFont: 'Courier New, monospace',
  companyNameSize: 30,
  companyNameWeight: 'bold',
  companyNameLetterSpacing: 2,
  companyNameGradient: false,
  companyNameGradientStart: '#ffffff',
  companyNameGradientEnd: '#03c6fc',
  
  bracketsShow: true,
  bracketsColor: '#03c6fc',
  bracketsType: 'angle' as const,
  
  cursorShow: true,
  cursorColor: '#ffffff',
  
  tagline: 'TECH SOLUTIONS',
  taglineColor: '#03c6fc',
  taglineFont: 'Arial, sans-serif',
  taglineSize: 14,
  taglineLetterSpacing: 1,
  taglineShow: true,
  
  iconName: 'Terminal',
  iconShow: false,
  iconColor: '#03c6fc',
  iconSize: 28,
  iconRotation: 0,
  iconAnimation: 'none' as const,
  iconPosition: 'left' as const,
  
  bgShape: 'rectangle' as const,
  bgGradientType: 'linear' as const,
  bgColorStart: '#0b4e8d',
  bgColorEnd: '#03c6fc',
  bgSolidColor: '#1e293b',
  bgGradientAngle: 135,
  borderRadius: 10,
  paddingX: 28,
  paddingY: 18,
  
  shadowColor: 'rgba(3, 198, 252, 0.5)',
  shadowBlur: 20,
  shadowSpread: 0,
  shadowOffsetY: 5,
  shadowOffsetX: 0,
  glowAnimation: true,
  glowDuration: 3,
  
  circuitShow: true,
  circuitColor: '#03c6fc',
  circuitOpacity: 0.2,
  circuitPattern: 'circuit' as const,
  
  binaryShow: true,
  binaryTextLeft: '10110',
  binaryTextRight: '01001',
  binaryColor: 'rgba(3, 198, 252, 0.2)',
  binarySize: 10,
  
  canvasColor: '#0f1218',

  // Split-text properties
  companyNameSplit: false,
  companyNamePart1: 'Reezma',
  companyNamePart2: 'Hanan',
  companyNameColorPart2: '#03c6fc',
  companyNameFontPart2: 'Courier New, monospace',
  companyNameWeightPart2: 'normal',
  companyNameGradientPart2: false,
  companyNameGradientStartPart2: '#ffffff',
  companyNameGradientEndPart2: '#03c6fc',

  // Custom Icon
  customIconSvg: '',
  customIconViewBox: '0 0 24 24',
};

export const PRESETS: Preset[] = [
  {
    id: 'Original',
    name: ' Original',
    description: 'The classic tech logo with angle brackets, circuit lines, and binary codes.',
    category: 'classic',
    config: { ...DEFAULT_CONFIG },
  },
  {
    id: 'neon-cyberpunk',
    name: 'Neon Cyberpunk',
    description: 'Vibrant neon colors with a floating CPU icon and square bracket code vibes.',
    category: 'cyberpunk',
    config: {
      ...DEFAULT_CONFIG,
      companyName: 'Reezma Hanan',
      companyNameColor: '#ff007f',
      companyNameFont: 'Fira Code, monospace',
      companyNameSize: 28,
      companyNameWeight: 'bold',
      companyNameLetterSpacing: 3,
      companyNameGradient: true,
      companyNameGradientStart: '#ff007f',
      companyNameGradientEnd: '#00f0ff',
      
      bracketsShow: true,
      bracketsColor: '#00f0ff',
      bracketsType: 'square' as const,
      
      cursorShow: true,
      cursorColor: '#00f0ff',
      
      tagline: 'DECENTRALIZED NETWORK',
      taglineColor: '#00f0ff',
      taglineFont: 'Courier New, monospace',
      taglineSize: 11,
      taglineLetterSpacing: 3,
      taglineShow: true,
      
      iconName: 'Cpu',
      iconShow: true,
      iconColor: '#ff007f',
      iconSize: 32,
      iconRotation: 45,
      iconAnimation: 'float' as const,
      iconPosition: 'top' as const,
      
      bgGradientType: 'linear' as const,
      bgColorStart: '#1d0030',
      bgColorEnd: '#000814',
      bgGradientAngle: 180,
      borderRadius: 16,
      paddingX: 36,
      paddingY: 24,
      
      shadowColor: 'rgba(255, 0, 127, 0.4)',
      shadowBlur: 30,
      shadowSpread: 2,
      shadowOffsetY: 0,
      shadowOffsetX: 0,
      glowAnimation: true,
      glowDuration: 2.5,
      
      circuitShow: true,
      circuitColor: '#ff007f',
      circuitOpacity: 0.15,
      circuitPattern: 'dots' as const,
      
      binaryShow: true,
      binaryTextLeft: '1101',
      binaryTextRight: 'E09A',
      binaryColor: 'rgba(0, 240, 255, 0.15)',
      binarySize: 11,
      
      canvasColor: '#07020d',
    },
  },
  {
    id: 'modern-corporate',
    name: 'Modern Corporate',
    description: 'Clean, reliable, and corporate design with a professional globe icon.',
    category: 'corporate',
    config: {
      ...DEFAULT_CONFIG,
      companyName: 'Reezma Hanan',
      companyNameColor: '#ffffff',
      companyNameFont: 'Outfit, sans-serif',
      companyNameSize: 32,
      companyNameWeight: 'bold',
      companyNameLetterSpacing: 1,
      companyNameGradient: false,
      
      bracketsShow: false,
      bracketsType: 'none' as const,
      
      cursorShow: false,
      
      tagline: 'CONSULTING SERVICES',
      taglineColor: '#94a3b8',
      taglineFont: 'Inter, sans-serif',
      taglineSize: 11,
      taglineLetterSpacing: 4,
      taglineShow: true,
      
      iconName: 'Globe',
      iconShow: true,
      iconColor: '#60a5fa',
      iconSize: 26,
      iconRotation: 0,
      iconAnimation: 'none' as const,
      iconPosition: 'left' as const,
      
      bgGradientType: 'linear' as const,
      bgColorStart: '#0f172a',
      bgColorEnd: '#1e293b',
      bgGradientAngle: 135,
      borderRadius: 8,
      paddingX: 32,
      paddingY: 20,
      
      shadowColor: 'rgba(15, 23, 42, 0.6)',
      shadowBlur: 15,
      shadowSpread: 0,
      shadowOffsetY: 6,
      shadowOffsetX: 0,
      glowAnimation: false,
      
      circuitShow: false,
      binaryShow: false,
      
      canvasColor: '#0b0f19',
    },
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    description: 'Warm color scheme featuring a sleek coding browser window icon.',
    category: 'creative',
    config: {
      ...DEFAULT_CONFIG,
      companyName: 'Reezma Hanan',
      companyNameColor: '#ffffff',
      companyNameFont: 'Montserrat, sans-serif',
      companyNameSize: 30,
      companyNameWeight: 'bold',
      companyNameLetterSpacing: 1,
      companyNameGradient: true,
      companyNameGradientStart: '#f59e0b',
      companyNameGradientEnd: '#ef4444',
      
      bracketsShow: false,
      bracketsType: 'none' as const,
      
      cursorShow: false,
      
      tagline: 'BUILDING FOR TOMORROW',
      taglineColor: '#fbcfe8',
      taglineFont: 'Outfit, sans-serif',
      taglineSize: 10,
      taglineLetterSpacing: 2.5,
      taglineShow: true,
      
      iconName: 'Code',
      iconShow: true,
      iconColor: '#f59e0b',
      iconSize: 28,
      iconRotation: 0,
      iconAnimation: 'pulse' as const,
      iconPosition: 'top' as const,
      
      bgGradientType: 'linear' as const,
      bgColorStart: '#4c0519',
      bgColorEnd: '#881337',
      bgGradientAngle: 45,
      borderRadius: 20,
      paddingX: 40,
      paddingY: 24,
      
      shadowColor: 'rgba(239, 68, 68, 0.4)',
      shadowBlur: 25,
      shadowSpread: 1,
      shadowOffsetY: 8,
      shadowOffsetX: 0,
      glowAnimation: true,
      glowDuration: 4,
      
      circuitShow: true,
      circuitColor: '#f59e0b',
      circuitOpacity: 0.1,
      circuitPattern: 'grid' as const,
      
      binaryShow: false,
      
      canvasColor: '#1c050e',
    },
  },
  {
    id: 'eco-tech',
    name: 'Eco Tech',
    description: 'A clean green-themed design for environmental and tech synergy.',
    category: 'creative',
    config: {
      ...DEFAULT_CONFIG,
      companyName: 'Reezma Hanan',
      companyNameColor: '#ffffff',
      companyNameFont: 'Outfit, sans-serif',
      companyNameSize: 28,
      companyNameWeight: 'bold',
      companyNameLetterSpacing: 2,
      companyNameGradient: true,
      companyNameGradientStart: '#a3e635',
      companyNameGradientEnd: '#10b981',
      
      bracketsShow: true,
      bracketsColor: '#34d399',
      bracketsType: 'curly' as const,
      
      cursorShow: true,
      cursorColor: '#34d399',
      
      tagline: 'SUSTAINABLE CODE',
      taglineColor: '#34d399',
      taglineFont: 'Inter, sans-serif',
      taglineSize: 11,
      taglineLetterSpacing: 3,
      taglineShow: true,
      
      iconName: 'Leaf',
      iconShow: true,
      iconColor: '#34d399',
      iconSize: 26,
      iconRotation: -15,
      iconAnimation: 'float' as const,
      iconPosition: 'left' as const,
      
      bgGradientType: 'linear' as const,
      bgColorStart: '#062f21',
      bgColorEnd: '#021f15',
      bgGradientAngle: 135,
      borderRadius: 12,
      paddingX: 30,
      paddingY: 20,
      
      shadowColor: 'rgba(16, 185, 129, 0.3)',
      shadowBlur: 20,
      shadowSpread: 0,
      shadowOffsetY: 6,
      shadowOffsetX: 0,
      glowAnimation: true,
      glowDuration: 3.5,
      
      circuitShow: true,
      circuitColor: '#10b981',
      circuitOpacity: 0.15,
      circuitPattern: 'circuit' as const,
      
      binaryShow: true,
      binaryTextLeft: '0010',
      binaryTextRight: '1100',
      binaryColor: 'rgba(165, 243, 85, 0.1)',
      binarySize: 10,
      
      canvasColor: '#010f0a',
    },
  },
  {
    id: 'terminal-split',
    name: 'Terminal Split',
    description: 'Tech-focused design utilizing the new split text typography styling.',
    category: 'classic',
    config: {
      ...DEFAULT_CONFIG,
      companyNameSplit: true,
      companyNamePart1: 'REEZMA',
      companyNamePart2: 'labs',
      companyNameColor: '#38bdf8',
      companyNameColorPart2: '#a78bfa',
      companyNameFont: 'Fira Code, monospace',
      companyNameFontPart2: 'Fira Code, monospace',
      companyNameWeight: 'bold',
      companyNameWeightPart2: 'normal',
      companyNameSize: 28,
      companyNameLetterSpacing: 1,
      
      bracketsShow: true,
      bracketsColor: '#64748b',
      bracketsType: 'square' as const,
      
      cursorShow: true,
      cursorColor: '#a78bfa',
      
      tagline: 'INNOVATION ENGINE',
      taglineColor: '#94a3b8',
      taglineFont: 'Inter, sans-serif',
      taglineSize: 11,
      taglineLetterSpacing: 3,
      taglineShow: true,
      
      iconName: 'Terminal',
      iconShow: true,
      iconColor: '#38bdf8',
      iconSize: 24,
      iconPosition: 'left' as const,
      iconAnimation: 'none' as const,
      
      bgGradientType: 'solid' as const,
      bgSolidColor: '#090d16',
      borderRadius: 12,
      paddingX: 30,
      paddingY: 20,
      
      shadowColor: 'rgba(56, 189, 248, 0.25)',
      shadowBlur: 25,
      shadowOffsetY: 8,
      glowAnimation: true,
      glowDuration: 4,
      
      circuitShow: true,
      circuitColor: '#38bdf8',
      circuitOpacity: 0.1,
      circuitPattern: 'grid' as const,
      
      binaryShow: false,
      canvasColor: '#04060b',
    },
  },
  {
    id: 'retro-wave',
    name: 'Retro Wave',
    description: 'Vaporwave aesthetics featuring sunset gradients and bold split lettering.',
    category: 'cyberpunk',
    config: {
      ...DEFAULT_CONFIG,
      companyNameSplit: true,
      companyNamePart1: 'NEON',
      companyNamePart2: 'DRIVE',
      companyNameColor: '#ff007f',
      companyNameColorPart2: '#00f0ff',
      companyNameFont: 'Orbitron, sans-serif',
      companyNameFontPart2: 'Orbitron, sans-serif',
      companyNameWeight: '900',
      companyNameWeightPart2: '400',
      companyNameSize: 32,
      companyNameLetterSpacing: 4,
      companyNameGradient: true,
      companyNameGradientStart: '#ff007f',
      companyNameGradientEnd: '#ff7700',
      companyNameGradientPart2: true,
      companyNameGradientStartPart2: '#00f0ff',
      companyNameGradientEndPart2: '#7000ff',
      
      bracketsShow: false,
      cursorShow: false,
      
      tagline: 'SYNTHESIZER DEPOT',
      taglineColor: '#f472b6',
      taglineFont: 'Syncopate, sans-serif',
      taglineSize: 9,
      taglineLetterSpacing: 5,
      taglineShow: true,
      
      iconName: 'Zap',
      iconShow: true,
      iconColor: '#00f0ff',
      iconSize: 28,
      iconPosition: 'top' as const,
      iconAnimation: 'pulse' as const,
      
      bgGradientType: 'linear' as const,
      bgColorStart: '#110022',
      bgColorEnd: '#000011',
      bgGradientAngle: 180,
      borderRadius: 4,
      paddingX: 40,
      paddingY: 24,
      
      shadowColor: 'rgba(255, 0, 127, 0.5)',
      shadowBlur: 35,
      shadowOffsetY: 0,
      glowAnimation: true,
      glowDuration: 2,
      
      circuitShow: true,
      circuitColor: '#ff007f',
      circuitOpacity: 0.15,
      circuitPattern: 'dots' as const,
      
      binaryShow: false,
      canvasColor: '#05000a',
    },
  },
  {
    id: 'luxury-gold',
    name: 'Luxury Gold',
    description: 'Elegant template showing contrasting text weighting with premium gold styling.',
    category: 'corporate',
    config: {
      ...DEFAULT_CONFIG,
      companyNameSplit: true,
      companyNamePart1: 'REEZMA',
      companyNamePart2: 'PRESTIGE',
      companyNameFont: 'Cinzel, serif',
      companyNameFontPart2: 'Inter, sans-serif',
      companyNameWeight: '900',
      companyNameWeightPart2: '300',
      companyNameSize: 24,
      companyNameLetterSpacing: 3,
      companyNameGradient: true,
      companyNameGradientStart: '#dfa735',
      companyNameGradientEnd: '#f8e08f',
      companyNameColorPart2: '#ffffff',
      
      bracketsShow: false,
      cursorShow: false,
      
      tagline: 'GLOBAL ESTATES & VENTURES',
      taglineColor: '#d1d5db',
      taglineFont: 'Cinzel, serif',
      taglineSize: 10,
      taglineLetterSpacing: 4,
      taglineShow: true,
      
      iconName: 'Star',
      iconShow: true,
      iconColor: '#f8e08f',
      iconSize: 22,
      iconPosition: 'left' as const,
      iconAnimation: 'none' as const,
      
      bgGradientType: 'linear' as const,
      bgColorStart: '#000000',
      bgColorEnd: '#1a1a1a',
      bgGradientAngle: 45,
      borderRadius: 0,
      paddingX: 32,
      paddingY: 20,
      
      shadowColor: 'rgba(223, 167, 53, 0.25)',
      shadowBlur: 30,
      shadowOffsetY: 8,
      glowAnimation: false,
      
      circuitShow: false,
      binaryShow: false,
      canvasColor: '#000000',
    },
  }
];
